import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import CustomHeader from '../../components/CustomHeader';

const AIHealthTipsScreen = ({ navigation }) => {
  const tips = [
    "Drink at least 8 glasses of water daily",
    "Walk 30 minutes every day to improve heart health",
    "Take medicines on time as prescribed by doctor",
    "Avoid junk food and include fresh fruits in diet",
    "Monitor blood pressure regularly if you have hypertension",
  ];

  return (
    <View style={styles.container}>
      <CustomHeader title="AI Health Tips" navigation={navigation} />

      <ScrollView contentContainerStyle={styles.content}>
        <Ionicons name="bulb-outline" size={80} color="#F59E0B" style={styles.icon} />
        
        <Text style={styles.title}>Personalized Health Tips</Text>
        <Text style={styles.subtitle}>Based on your health profile</Text>

        {tips.map((tip, index) => (
          <View key={index} style={styles.tipCard}>
            <Ionicons name="checkmark-circle" size={26} color="#10B981" />
            <Text style={styles.tipText}>{tip}</Text>
          </View>
        ))}

        <TouchableOpacity style={styles.refreshBtn} onPress={() => alert("New tips generated by AI")}>
          <Text style={styles.refreshText}>Get New Tips</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 20, alignItems: 'center' },
  icon: { marginBottom: 20 },
  title: { fontSize: 26, fontWeight: 'bold', color: '#1E3A8A' },
  subtitle: { fontSize: 16, color: '#64748B', marginBottom: 30 },
  tipCard: {
    backgroundColor: '#fff',
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    elevation: 3,
  },
  tipText: { flex: 1, marginLeft: 15, fontSize: 16, color: '#334155' },
  refreshBtn: {
    backgroundColor: '#00D4FF',
    padding: 16,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
    marginTop: 25,
  },
  refreshText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
});

export default AIHealthTipsScreen;